### ISSUE TITLE
Output is Black on Black in VS Code

### ISSUE THREAD

**Issue by eightbit** [sphinx-doc/sphinx-autobuild#107]
**Thanks so much for providing this great tool!**

**Describe the bug**

When I run auto build in VS Code, much of the output is almost the same black color as the background of the terminal.
After terminating the server, invoking 'Crtl-C' a couple of times is required to restore the default color to the terminal prompt.

**To Reproduce**

Run the code:
`sphinx-autobuild . --port 8020 _build/html`

**Expected behavior**

Expect the terminal output text to be default color - almost white.

**Environment**
- VS Code  1.54.1
- Python Version [e.g. 3.8.5]:
- Win 10 - 10.0.19041

![sphxAutoBld01](https://user-images.githubusercontent.com/5913748/110966306-bdb3d600-831a-11eb-8534-255d91559d42.png)

**Comment by pradyunsg** [comment]
This is not related to this tool itself, but rather the colors are controlled by your VS Code theme: this theme is merely telling the terminal to "show this as cyan/blue etc", and your VS Code configuration is presenting that as a color with really low contrast.

Further, since this issue was filed, VS Code has fixed this on their end by enforcing minimum contrast on output by default: https://code.visualstudio.com/docs/terminal/appearance#_minimum-contrast-ratio
